// AUTO-GENERATED by v2calc: inert vtable/typeinfo anchors for the UI
// classes that Build reaches only through dynamic_cast (never executed
// headless - AfxGetMainWnd() is null). Generated from the pane/app
// headers so the linker can emit each class vtable + typeinfo.
#include "stdafx.h"
#include "DDOBuilder.h"
#include "GrantedFeatsPane.h"
#include "MainFrm.h"
#include "StancesPane.h"

// Slider lookups from Effect::TotalAmount/StacksAsString reach the stances pane;
// headless there is no slider UI, so report "no slider" (effect falls back to its
// own stack count). The pane methods above are never executed (main window null).
const SliderItem* CStancesPane::GetSlider(const std::string&) const { return nullptr; }

void CStancesPane::OnInitialUpdate() {}
void CStancesPane::DoDataExchange(CDataExchange* pDX) {}
void CStancesPane::UpdateActiveBuildChanged(Character* pCharacter) {}
void CStancesPane::UpdateAlignmentChanged(Life*, AlignmentType) {}
void CStancesPane::UpdateRaceChanged(Life*, const std::string&) {}
void CStancesPane::UpdateClassChanged(Build*, const std::string& classFrom, const std::string& classTo, size_t level) {}
void CStancesPane::UpdateNewStance(Build*, const Stance&) {}
void CStancesPane::UpdateRevokeStance(Build*, const Stance&) {}
void CStancesPane::UpdateFeatTrained(Build*, const std::string& featName) {}
void CStancesPane::UpdateFeatRevoked(Build*, const std::string& featName) {}
void CStancesPane::UpdateStanceActivated(Build*, const std::string& stanceName) {}
void CStancesPane::UpdateStanceDeactivated(Build*, const std::string& stanceName) {}
void CStancesPane::UpdateStanceDisabled(Build*, const std::string& stanceName) {}
void CStancesPane::UpdateEnhancementEffectApplied(Build*, const Effect& effect) {}
void CStancesPane::UpdateEnhancementEffectRevoked(Build*, const Effect& effect) {}
void CStancesPane::UpdateFeatEffectApplied(Build*, const Effect& effect) {}
void CStancesPane::UpdateFeatEffectRevoked(Build*, const Effect& effect) {}
void CStancesPane::UpdateItemEffectApplied(Build*, const Effect& effect) {}
void CStancesPane::UpdateItemEffectRevoked(Build*, const Effect& effect) {}
void CStancesPane::UpdateGearChanged(Build*, InventorySlotType) {}
void CGrantedFeatsPane::OnInitialUpdate() {}
void CGrantedFeatsPane::DoDataExchange(CDataExchange* pDX) {}
void CGrantedFeatsPane::UpdateActiveLifeChanged(Character*) {}
void CGrantedFeatsPane::UpdateActiveBuildChanged(Character*) {}
void CGrantedFeatsPane::BuildLevelChanged(Build*) {}
void CGrantedFeatsPane::ClassChanged(Build*, const std::string&, const std::string&, size_t) {}
void CGrantedFeatsPane::FeatTrained(Build*, const std::string&) {}
void CGrantedFeatsPane::FeatRevoked(Build*, const std::string&) {}
void CGrantedFeatsPane::RaceChanged(Life*, const std::string&) {}
void CGrantedFeatsPane::FeatEffectApplied(Build*, const Effect& effect) {}
void CGrantedFeatsPane::FeatEffectRevoked(Build*, const Effect& effect) {}
void CGrantedFeatsPane::ItemEffectApplied(Build*, const Effect& effect) {}
void CGrantedFeatsPane::ItemEffectRevoked(Build*, const Effect& effect) {}
void CGrantedFeatsPane::ItemEffectApplied(Build*, const Effect& effect, WeaponType wt) {}
void CGrantedFeatsPane::ItemEffectRevoked(Build*, const Effect& effect, WeaponType wt) {}
void CGrantedFeatsPane::EnhancementTrained(Build*, const EnhancementItemParams& item) {}
void CGrantedFeatsPane::EnhancementRevoked(Build*, const EnhancementItemParams& item) {}
void CGrantedFeatsPane::EnhancementEffectApplied(Build*, const Effect& effect) {}
void CGrantedFeatsPane::EnhancementEffectRevoked(Build*, const Effect& effect) {}
void CGrantedFeatsPane::StanceActivated(Build* charData, const std::string& stanceName) {}
void CGrantedFeatsPane::StanceDeactivated(Build* charData, const std::string& stanceName) {}
void CGrantedFeatsPane::SliderChanged(Build* charData, const std::string& sliderName, int newValue) {}
void CGrantedFeatsPane::GearChanged(Build* pBuild, InventorySlotType slot) {}
BOOL CMainFrame::PreCreateWindow(CREATESTRUCT& cs) { return 0; }
void CMainFrame::GetMessageString(UINT nID, CString& rMessage) const {}
BOOL CDDOBuilderApp::InitInstance() { return 0; }
int CDDOBuilderApp::ExitInstance() { return 0; }
void CDDOBuilderApp::PreLoadState() {}
void CDDOBuilderApp::LoadCustomState() {}
void CDDOBuilderApp::SaveCustomState() {}
UINT CDDOBuilderApp::GetProfileInt(LPCTSTR lpszSection, LPCTSTR lpszEntry, int nDefault) { return 0; }
BOOL CDDOBuilderApp::WriteProfileInt(LPCTSTR lpszSection, LPCTSTR lpszEntry, int nValue) { return 0; }
CString CDDOBuilderApp::GetProfileString(LPCTSTR lpszSection, LPCTSTR lpszEntry, LPCTSTR lpszDefault ) { return CString(); }
BOOL CDDOBuilderApp::WriteProfileString(LPCTSTR lpszSection, LPCTSTR lpszEntry, LPCTSTR lpszValue) { return 0; }
BOOL CDDOBuilderApp::GetProfileBinary(LPCTSTR lpszSection, LPCTSTR lpszEntry, LPBYTE* ppData, UINT* pBytes) { return 0; }
BOOL CDDOBuilderApp::WriteProfileBinary(LPCTSTR lpszSection, LPCTSTR lpszEntry, LPBYTE pData, UINT nBytes) { return 0; }

// destructors (vtable key methods) + the specific members Build references
CStancesPane::~CStancesPane() {}
CGrantedFeatsPane::~CGrantedFeatsPane() {}
CMainFrame::~CMainFrame() {}

bool CStancesPane::IsStanceActive(const std::string&, WeaponType) const { return false; }
void CStancesPane::UpdateGreensteelStances() {}
bool CGrantedFeatsPane::IsGrantedFeat(const std::string&) const { return false; }
BOOL CMainFrame::LoadFrame(UINT, DWORD, CWnd*, CCreateContext*) { return FALSE; }
BOOL CMainFrame::OnCmdMsg(UINT, int, void*, AFX_CMDHANDLERINFO*) { return FALSE; }
CFormView* CMainFrame::GetPaneView(const CRuntimeClass*) { return nullptr; }
bool CDDOBuilderApp::LamanniaMode() const { return false; }
